let music = [
    {
        id: 0,
        name : "Ae Dil Hai Mushkil",
        artist : "Arijit Singh",
        movie: "Ae Dil Hai Mushkil",
        lang : "Hindi",
        img : "Ae Dil Hai Mushkil.jpg",
        type : "",
        filename : "Ae Dil Hai Muskhil.mp3",
        timesPlayed : 0,
    },
    {
        id: 1,
        name : "Arcade",
        artist : "Duncan Laurence",
        movie: "Artist Single",
        lang : "English",
        img : "Arcade.jpg",
        type : "",
        filename : "Arcade.mp3",
        timesPlayed : 0,
    },
    {
        id: 2,
        name : "Badtameez Dil",
        artist : "Benny Dayal",
        movie: "Yeh Jawaani Hai Deewani",
        lang : "Hindi",
        img : "Badtameez Dil.jpg",
        type : "",
        filename : "Badtameez Dil.mp3",
        timesPlayed : 0,
    },
    {
        id: 3,
        name : "Besharam Rang",
        artist : "Vishal & Shekhar",
        movie: "Pathaan",
        lang : "Hindi",
        img : "Besharam Rang.jpg",
        type : "",
        filename : "Besharam Rang.mp3",
        timesPlayed : 0,
    },
    {
        id: 4,
        name : "Blue Eyes",
        artist : "Yo Yo Honey Singh",
        movie: "Artist Single",
        lang : "Hindi",
        img : "Blue Eyes.jpg",
        type : "",
        filename : "Blue Eyes.mp3",
        timesPlayed : 0,
    },
    {
        id: 5,
        name : "Chammak Challo",
        artist : "AKON",
        movie: "Ra-One",
        lang : "Hindi",
        img : "Chammak Challo.jpg",
        type : "",
        filename : "Chammak Challo.mp3",
        timesPlayed : 0,
    },
    {
        id: 6,
        name : "Crazy In Love",
        artist : "Sofia Kelberg",
        movie: "Fifty Shades of Grey",
        lang : "English",
        img : "Crazy In Love.jpg",
        type : "",
        filename : "Crazy In Love.mp3",
        timesPlayed : 0,
    },
    {
        id: 7,
        name : "Doobey",
        artist : "OAFF & Savera",
        movie: "Gehrai",
        lang : "Hindi",
        img : "Doobey.jpg",
        type : "",
        filename : "Doobey.mp3",
        timesPlayed : 0,
    },
    {
        id: 8,
        name : "Dusk Till Dawn",
        artist : "Zayn & Sia",
        movie: "Artist Single",
        lang : "English",
        img : "Dusk Till Dawn.jpg",
        type : "",
        filename : "Dusk Till Dawn.mp3",
        timesPlayed : 0,
    },
    {
        id: 9,
        name : "Electric Love",
        artist : "BORNS",
        movie: "Artist Single",
        lang : "English",
        img : "Electric Love.jpg",
        type : "",
        filename : "Electric Love.mp3",
        timesPlayed : 0,
    },
    {
        id: 10,
        name : "Gimme More",
        artist : "Britney Spears",
        movie: "Artist Single",
        lang : "English",
        img : "Gimme More.jpg",
        type : "",
        filename : "Gimme More.mp3",
        timesPlayed : 0,
    },
    {
        id: 11,
        name : "Harleys In Hawaii",
        artist : "Katy Perry",
        movie: "Artist Single",
        lang : "English",
        img : "Harleys In Hawaii.jpg",
        type : "",
        filename : "Harleys In Hawaii.mp3",
        timesPlayed : 0,
    },
    {
        id: 12,
        name : "Heat Waves",
        artist : "Glass Animals",
        movie: "Artist Single",
        lang : "English",
        img : "Heat Waves.jpg",
        type : "",
        filename : "Heat Waves.mp3",
        timesPlayed : 0,
    },
    {
        id: 13,
        name : "Kaise Hua",
        artist : "Vishal Mishra",
        movie: "Kabir Singh",
        lang : "Hindi",
        img : "Kaise Hua.jpg",
        type : "",
        filename : "Kaise Hua.mp3",
        timesPlayed : 0,
    },
    {
        id: 14,
        name : "Kesariya",
        artist : "Arijit Singh",
        movie: "Brahmastra",
        lang : "Hindi",
        img : "Kesariya.jpg",
        type : "",
        filename : "Kesariya.mp3",
        timesPlayed : 0,
    },
    {
        id: 15,
        name : "Love Your Voice",
        artist : "Jony",
        movie: "Artist Single",
        lang : "English",
        img : "Love Your Voice.jpg",
        type : "",
        filename : "Love Your Voice.mp3",
        timesPlayed : 0,
    },
    {
        id: 16,
        name : "Once Upon A Time",
        artist : "Anirudh Ravichander",
        movie: "Vikram",
        lang : "English",
        img : "Once Upon A Time.jpg",
        type : "",
        filename : "Once Upon A Time.mp3",
        timesPlayed : 0,
    },
    {
        id: 17,
        name : "Param Sundari",
        artist : "A R Rahman & Shreya Goshal",
        movie: "Mimi",
        lang : "Hindi",
        img : "Param Sundari.jpg",
        type : "",
        filename : "Param Sundari.mp3",
        timesPlayed : 0,
    },
    {
        id: 18,
        name : "Peaches",
        artist : "Justin Beiber",
        movie: "Artist Single",
        lang : "English",
        img : "Peaches.jpg",
        type : "",
        filename : "Peaches.mp3",
        timesPlayed : 0,
    },
    {
        id: 19,
        name : "Senorita",
        artist : "Camilia Cabello",
        movie: "Artist Single",
        lang : "English",
        img : "Senorita.jpg",
        type : "",
        filename : "Senorita.mp3",
        timesPlayed : 0,
    },
    {
        id: 20,
        name : "Sugar & Brownies",
        artist : "DHARIA",
        movie: "Artist Single",
        lang : "English",
        img : "Sugar & Brownies.jpg",
        type : "",
        filename : "Sugar & Brownies.mp3",
        timesPlayed : 0,
    },
    {
        id: 21,
        name : "The Humma Song",
        artist : "A R Rahman",
        movie: "Ok Jaanu",
        lang : "Hindi",
        img : "The Humma Song.jpg",
        type : "",
        filename : "The Humma Song.mp3",
        timesPlayed : 0,
    },
    {
        id: 22,
        name : "Tum Hi Ho",
        artist : "Arijit Singh",
        movie: "Aashiqui 2",
        lang : "Hindi",
        img : "Tum Hi Ho.jpg",
        type : "",
        filename : "Tum Hi Ho.mp3",
        timesPlayed : 0,
    },
    {
        id: 23,
        name : "Under the Influence",
        artist : "Chris Brown",
        movie: "Artist Single",
        lang : "English",
        img : "Under The Influence.jpg",
        type : "",
        filename : "Under The Influence.mp3",
        timesPlayed : 0,
    },
    {
        id: 24,
        name : "Woman",
        artist : "Doja Cat",
        movie: "Artist Single",
        lang : "English",
        img : "Woman.jpg",
        type : "",
        filename : "Woman.mp3",
        timesPlayed : 0,
    }

];

export default music;