let music = [
    {
        id: 0,
        name : "Ae Dil Hai Mushkil",
        artist : "Arijit Singh",
        movie: "Ae Dil Hai Mushkil",
        lang : "Hindi",
        img : "src/images/Ae-Dil-Hai-Mushkil.jpg",
        type : "",
        filename : "Ae Dil Hai Muskhil.mp3",
        timesPlayed : 0,
    },
    {
        id: 1,
        name : "Arcade",
        artist : "Duncan Laurence",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "Arcade.mp3",
        timesPlayed : 0,
    },
    {
        id: 2,
        name : "Badtameez Dil",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "Badtameez Dil.mp3",
        timesPlayed : 0,
    },
    {
        id: 3,
        name : "Besharam Rang",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "Besharam Rang.mp3",
        timesPlayed : 0,
    },
    {
        id: 4,
        name : "Blue Eyes",
        artist : "Yo Yo Honey Singh",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 5,
        name : "Chammak Challo",
        artist : "",
        movie: "Ra-One",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 6,
        name : "Crazy In Love",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 7,
        name : "Doobey",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 8,
        name : "Dusk Till Dawn",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 9,
        name : "Electric Love",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 10,
        name : "Gimme More",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 11,
        name : "Harleys In Hawaii",
        artist : "Katy Perry",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 12,
        name : "Heat Waves",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 13,
        name : "Kaise Hua",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 14,
        name : "Kesariya",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 15,
        name : "Love Your Voice",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 16,
        name : "Once Upon A Time",
        artist : "",
        movie: "Vikram",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 17,
        name : "Param Sundari",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 18,
        name : "Peaches",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 19,
        name : "Senorita",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 20,
        name : "Sugar & Brownies",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 21,
        name : "The Humma Song",
        artist : "",
        movie: "",
        lang : "Hindi",
        img : "",
        type : "",
        filename : "",
        timesPlayed : 0,
    },
    {
        id: 22,
        name : "Tum Hi Ho",
        artist : "",
        movie: "",
        lang : "",
        img : "",
        type : "",
        filename : "",
        timesPlayed : "",
    },
    {
        id: 23,
        name : "Under the Influence",
        artist : "",
        movie: "",
        lang : "English",
        img : "",
        type : "",
        filename : "Under The Influence.mp3",
        timesPlayed : 0,
    },
    {
        id: 24,
        name : "Woman",
        artist : "Doja Cat",
        movie: ".",
        lang : "English",
        img : "",
        type : "",
        filename : "Woman.mp3",
        timesPlayed : 0,
    }

];

export default music;